/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Builder.mapa.Mapa1;
import Builder.mapa.Mapa2;
import Builder.mapa.Mapa3;
import Builder.mapa.Mapa4;
import Builder.mapa.Mapa5;
import Observer.ObservadorEscolhaMapa;
import Singleton.PersonagensJogo;
import controler.ControladorEscolhaMapa;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Aners
 */
public class escolhaMapa extends javax.swing.JFrame implements ObservadorEscolhaMapa {

    private ControladorEscolhaMapa uc;
    private mapaJogo mp = new mapaJogo();
    private previewMapa ep = new previewMapa();

    /**
     * Creates new form NewJFrame
     */
    public escolhaMapa() {
        this.uc = new ControladorEscolhaMapa();
        this.uc.anexar(this);
        initComponents();
        btnPreviewMapa1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ep.exibirTela(new Mapa1());
            }
        });
        btnPreviewMapa2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ep.exibirTela(new Mapa2());
            }
        });
        btnPreviewMapa3.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ep.exibirTela(new Mapa3());
            }
        });
        btnPreviewMapa4.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ep.exibirTela(new Mapa4());
            }
        });
        btnPreviewMapa5.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ep.exibirTela(new Mapa5());
            }
        });
        btnEscolha1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                uc.salvarMapa(new Mapa1());
            }
        });
        btnEscolha2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                uc.salvarMapa(new Mapa2());
            }
        });
        btnEscolha3.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                uc.salvarMapa(new Mapa3());
            }
        });
        btnEscolha4.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                uc.salvarMapa(new Mapa4());
            }
        });
        btnEscolha5.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                uc.salvarMapa(new Mapa5());
            }
        });
        btnContinuar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                uc.verificaTela();
            }
        });
    }

    @Override
    public void mostrarMensagem(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPreviewMapa4 = new javax.swing.JButton();
        btnPreviewMapa1 = new javax.swing.JButton();
        btnPreviewMapa2 = new javax.swing.JButton();
        btnPreviewMapa3 = new javax.swing.JButton();
        btnPreviewMapa5 = new javax.swing.JButton();
        btnContinuar = new javax.swing.JButton();
        btnEscolha1 = new javax.swing.JButton();
        btnEscolha2 = new javax.swing.JButton();
        btnEscolha3 = new javax.swing.JButton();
        btnEscolha4 = new javax.swing.JButton();
        btnEscolha5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPreviewMapa4.setText("PREVIEW MAPA 4");

        btnPreviewMapa1.setText("PREVIEW MAPA 1");

        btnPreviewMapa2.setText("PREVIEW MAPA 2");

        btnPreviewMapa3.setText("PREVIEW MAPA 3");

        btnPreviewMapa5.setText("PREVIEW MAPA 5");

        btnContinuar.setText("CONTINUAR");

        btnEscolha1.setText("ESCOLHER MAPA");

        btnEscolha2.setText("ESCOLHER MAPA");

        btnEscolha3.setText("ESCOLHER MAPA");

        btnEscolha4.setText("ESCOLHER MAPA");

        btnEscolha5.setText("ESCOLHER MAPA");

        jLabel1.setText("MAPA 1: Mapa com 1 terreno.");

        jLabel2.setText("MAPA 2: Mapa com 2 terrenos.");

        jLabel3.setText("MAPA 3: Mapa com 3 terrenos.");

        jLabel4.setText("MAPA 4: Mapa com 4 terrenos.");

        jLabel5.setText("MAPA 5: Mapa com 5 terrenos.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnPreviewMapa5, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(btnPreviewMapa4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(btnPreviewMapa3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPreviewMapa2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPreviewMapa1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEscolha5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEscolha4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEscolha3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEscolha2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEscolha1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnContinuar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPreviewMapa1)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPreviewMapa2)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPreviewMapa3)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPreviewMapa4)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPreviewMapa5)
                            .addComponent(jLabel5)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnEscolha1)
                        .addGap(18, 18, 18)
                        .addComponent(btnEscolha2)
                        .addGap(18, 18, 18)
                        .addComponent(btnEscolha3)
                        .addGap(18, 18, 18)
                        .addComponent(btnEscolha4)
                        .addGap(18, 18, 18)
                        .addComponent(btnEscolha5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(btnContinuar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(escolhaMapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(escolhaMapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(escolhaMapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(escolhaMapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new escolhaMapa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnEscolha1;
    private javax.swing.JButton btnEscolha2;
    private javax.swing.JButton btnEscolha3;
    private javax.swing.JButton btnEscolha4;
    private javax.swing.JButton btnEscolha5;
    private javax.swing.JButton btnPreviewMapa1;
    private javax.swing.JButton btnPreviewMapa2;
    private javax.swing.JButton btnPreviewMapa3;
    private javax.swing.JButton btnPreviewMapa4;
    private javax.swing.JButton btnPreviewMapa5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

    public void exibirTela() {
        setVisible(true);
        getContentPane().setBackground(PersonagensJogo.getInstance().getCorFundo());
    }

    @Override
    public void exibirProxTela() {
        mp.exibirTela();
    }

}
