/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Singleton.PersonagensJogo;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import model.Personagem;

/**
 *
 * @author Aners
 */
public class InfoPersonagem extends javax.swing.JFrame {

    private JLabel l = new JLabel();
    private JLabel lClasse = new JLabel();
    private JLabel lVida = new JLabel();
    private JLabel lAtaque = new JLabel();
    private JLabel lPV = new JLabel();
    private JLabel lPontos = new JLabel();
    private JLabel lMovimento = new JLabel();

    public InfoPersonagem() {
        initComponents();
        jPanel1.add(l);
        jPanel1.add(lClasse);
        jPanel1.add(lVida);
        jPanel1.add(lAtaque);
        jPanel1.add(lPV);
        jPanel1.add(lMovimento);
        jPanel1.add(lPontos);
    }

    public void exibirTela(Personagem p) {
        setVisible(true);
        getContentPane().setBackground(PersonagensJogo.getInstance().getCorFundo());
        getContentPane().setFont(PersonagensJogo.getInstance().getFonte());
        l.setIcon(new ImageIcon(new ImageIcon(p.getFotoPersonagem()).getImage().getScaledInstance(64, 64, Image.SCALE_DEFAULT)));
        l.setBounds(50, 30, 64, 64);
        lClasse.setText(p.nomeClasse());
        lClasse.setBounds(50, 10, 100, 20);
        lVida.setText("Vida: " + p.getVida());
        lVida.setBounds(20, 100, 100, 20);
        lAtaque.setText("Ataque: " + p.getForcaAtaque());
        lAtaque.setBounds(20, 120, 100, 20);
        lPV.setText("Pontos de Vitória: " + p.getCustoVP());
        lPV.setBounds(20, 140, 130, 20);
        lMovimento.setText("Movimentação: " + p.getMovimentacao());
        lMovimento.setBounds(20, 160, 130, 20);
        lPontos.setText("Frente: " + p.getFrente() + " Costas: " + p.getCostas() + " Lados: " + p.getEsquerda());
        lPontos.setBounds(20, 180, 200, 20);
    }

    public void desenhaTodos() {
//        int xAux = 0;
//        int yAux = 0;
//        int aux = 0;
//        for (Personagem p : PersonagensJogo.getInstance().getPersonagens()) {
//            labels.add(new JLabel());
//            labels.get(aux).setIcon(new ImageIcon(new ImageIcon(p.getFotoPersonagem()).getImage().getScaledInstance(64, 64, Image.SCALE_DEFAULT)));
//            labels.get(aux).setBounds(xAux, yAux, 64, 64);
//            jPanel1.add(labels.get(aux));
//            aux += 1;
//            xAux += 1;
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 189, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoPersonagem.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoPersonagem.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoPersonagem.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoPersonagem.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoPersonagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
